//! Text (and JSON) writers for a finished dump.

use crate::analysis::{Access, Trivial};
use crate::dump::{LayoutStatus, Report};
use crate::model::{Module, NameSrc};
use crate::names;
use anyhow::Result;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;

fn hex(v: u64) -> String {
    format!("0x{v:X}")
}

fn func_name(m: &Module, rva: u32) -> String {
    m.names.get(&rva).map(|n| n.name.clone()).unwrap_or_else(|| format!("sub_{rva:X}"))
}

fn ts(t: u32) -> String {
    // Civil date from a unix timestamp (UTC).
    let days = t as i64 / 86400;
    let secs = t as i64 % 86400;
    let z = days + 719468;
    let era = z.div_euclid(146097);
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{y:04}-{m:02}-{d:02} {:02}:{:02}:{:02} UTC", secs / 3600, secs / 60 % 60, secs % 60)
}

pub fn write_all(r: &Report, out: &Path, sigs: &[crate::sigs::Sig], extras: &[crate::sigs::Extra], failed: &[String]) -> Result<()> {
    std::fs::create_dir_all(out)?;
    std::fs::write(out.join("offsets.txt"), offsets_txt(r))?;
    std::fs::write(out.join("vtables.txt"), vtables_txt(r))?;
    std::fs::write(out.join("functions.txt"), functions_txt(r))?;
    std::fs::write(out.join("globals.txt"), globals_txt(r))?;
    std::fs::write(out.join("strings.txt"), strings_txt(r))?;
    std::fs::write(out.join("imports_exports.txt"), imports_exports_txt(r))?;
    let mut s = String::new();
    let exe = &r.world.modules[r.exe];
    let _ = writeln!(s, "# gddumper signatures for {} (PE timestamp {:#x}, {})", exe.pe.name, exe.pe.timestamp, ts(exe.pe.timestamp));
    let _ = writeln!(s, "# Feed this file back with `gddumper dump --sigs <file>` after a game update to recover names.");
    let _ = writeln!(s, "# {} patterns, {} fallback records, {} names without either", sigs.len(), extras.len(), failed.len());
    let mut cur = crate::sigs::DEFAULT_MODULE.to_string();
    for g in sigs {
        if g.module != cur {
            cur = g.module.clone();
            let _ = writeln!(s, "\n[{cur}]");
        }
        let _ = writeln!(s, "{}", g.to_line());
    }
    if cur != crate::sigs::DEFAULT_MODULE && !extras.is_empty() {
        let _ = writeln!(s, "\n[{}]", crate::sigs::DEFAULT_MODULE);
    }
    if !extras.is_empty() {
        let _ = writeln!(s, "\n# fallbacks: vtable slot index / offset relative to another named field");
        for e in extras {
            let _ = writeln!(s, "{}", e.to_line());
        }
    }
    if !failed.is_empty() {
        let _ = writeln!(s, "\n# no unique signature:");
        for f in failed {
            let _ = writeln!(s, "#   {f}");
        }
    }
    std::fs::write(out.join("signatures.txt"), s)?;
    std::fs::write(out.join("dump.json"), serde_json::to_string_pretty(&json(r))?)?;
    Ok(())
}

fn header(r: &Report, s: &mut String) {
    let _ = writeln!(s, "Geometry Dash dump — generated by gddumper {}", env!("CARGO_PKG_VERSION"));
    let _ = writeln!(s, "All addresses are RVAs (offsets from the module base): absolute = base + RVA.");
    let _ = writeln!(s);
    for m in &r.world.modules {
        let _ = writeln!(
            s,
            "  {:<20} timestamp {:#010x} ({})  image base {:#x}  size {:#x}  entry {:#x}",
            m.pe.name,
            m.pe.timestamp,
            ts(m.pe.timestamp),
            m.pe.image_base,
            m.pe.size_of_image,
            m.pe.entry
        );
    }
    if let Some(b) = &r.bindings {
        let _ = writeln!(
            s,
            "\n  bindings: {}  ({}/{} addresses match = {:.1}%, {})",
            b.source,
            b.hits,
            b.checked,
            100.0 * b.hits as f64 / b.checked.max(1) as f64,
            if b.applied { "applied" } else { "NOT applied: different game version" }
        );
    }
    if !r.sig_results.is_empty() {
        let ok = r.sig_results.iter().filter(|x| x.value.is_some()).count();
        let _ = writeln!(s, "  signatures: {ok}/{} resolved", r.sig_results.len());
    }
    if r.user_names > 0 {
        let _ = writeln!(s, "  user names: {}", r.user_names);
    }
    let _ = writeln!(s);
}

pub fn offsets_txt(r: &Report) -> String {
    let mut s = String::new();
    header(r, &mut s);
    let w = &r.world;

    let _ = writeln!(s, "==================================================================");
    let _ = writeln!(s, " SINGLETONS / INSTANCE GLOBALS   (pointer to the object lives at module+global)");
    let _ = writeln!(s, "==================================================================");
    for (mi, m) in w.modules.iter().enumerate() {
        for sg in &m.best_singletons() {
            let _ = writeln!(
                s,
                "  {:<34} {}+{:<10} accessor {:<44} sizeof {}",
                sg.class.clone().unwrap_or_else(|| "<unknown class>".into()),
                m.pe.name,
                hex(sg.global as u64),
                format!("{} ({})", func_name(m, sg.accessor), hex(sg.accessor as u64)),
                hex(sg.size)
            );
        }
        for g in &m.instance_globals {
            let _ = writeln!(
                s,
                "  {:<34} {}+{:<10} stored by {} ({})",
                g.class,
                m.pe.name,
                hex(g.global as u64),
                func_name(m, g.func),
                hex(g.func as u64)
            );
        }
        let _ = mi;
    }
    for ((mi, g), n) in &r.named_globals {
        let m = &w.modules[*mi];
        if m.singletons.iter().any(|x| x.global == *g) || m.instance_globals.iter().any(|x| x.global == *g) {
            continue;
        }
        let _ = writeln!(s, "  {:<34} {}+{}", n, m.pe.name, hex(*g as u64));
    }
    let _ = writeln!(s);

    let _ = writeln!(s, "==================================================================");
    let _ = writeln!(s, " CLASSES");
    let _ = writeln!(s, "==================================================================");
    let _ = writeln!(s, " field columns: offset  size  type-hint  reads/writes/addr-taken  #funcs  name");
    let _ = writeln!(s, " names: [B] Geode bindings layout, [S] signature, [U] user, (get/set) accessor-derived");
    let _ = writeln!(s);

    let mut all: BTreeSet<String> = w.classes.iter().filter(|(_, c)| c.module.is_some() || c.size.is_some()).map(|(n, _)| n.clone()).collect();
    all.extend(w.fields.keys().cloned());
    all.extend(r.named_fields.keys().cloned());
    for cname in &all {
        let cv = w.classes.get(cname);
        let mi = cv.and_then(|c| c.module);
        let module_name = mi.map(|i| w.modules[i].pe.name.as_str()).unwrap_or("-");
        let _ = write!(s, "class {cname}");
        if let Some(c) = cv {
            if !c.direct_bases.is_empty() {
                let b: Vec<String> = c.direct_bases.iter().map(|b| format!("{} @{}", b.name, hex(b.mdisp as u64))).collect();
                let _ = write!(s, " : {}", b.join(", "));
            }
        }
        let _ = writeln!(s);
        let _ = write!(s, "    module {module_name}");
        if let Some(c) = cv {
            match c.size {
                Some(sz) => {
                    let info = mi.and_then(|i| w.modules[i].sizes.get(cname));
                    let src = info.map(|x| x.source).unwrap_or("?");
                    let _ = write!(s, "   sizeof {} ({src})", hex(sz));
                    if let Some(i) = info {
                        let others: Vec<String> = i.observed.keys().filter(|v| **v != sz).map(|v| hex(*v)).collect();
                        if !others.is_empty() {
                            let _ = write!(s, " [other allocation sizes seen: {}]", others.join(", "));
                        }
                    }
                }
                None => {
                    if let Some(g) = c.inferred_size {
                        let _ = write!(s, "   sizeof <= {} (layout gap)", hex(g));
                    }
                }
            }
        }
        if let Some(st) = r.layout_status.get(cname) {
            let _ = write!(
                s,
                "   bindings layout: {}",
                match st {
                    LayoutStatus::Verified { size } if r.bindings.as_ref().is_some_and(|b| b.applied) =>
                        format!("VERIFIED (ends at {})", hex(*size)),
                    LayoutStatus::Verified { size } => format!("size matches (ends at {}), bindings are from another build", hex(*size)),
                    LayoutStatus::Mismatch { computed, measured } =>
                        format!("MISMATCH (computed {} vs measured {}) — names may be shifted", hex(*computed), hex(*measured)),
                    LayoutStatus::Unmeasured { computed } => format!("unchecked (ends at {})", hex(*computed)),
                    LayoutStatus::Failed(e) => format!("incomplete ({e})"),
                }
            );
        }
        let _ = writeln!(s);
        if let Some(i) = mi {
            let m = &w.modules[i];
            if let Some(c) = m.rtti.class(cname) {
                let _ = writeln!(s, "    typeinfo {}", hex(c.td_rva as u64));
                for v in &c.vtables {
                    let _ = writeln!(s, "    vtable   {}  (subobject +{}, {} slots)", hex(v.rva as u64), hex(v.offset as u64), v.entries.len());
                }
            }
            let structors: Vec<String> = m
                .ctors
                .iter()
                .filter(|(_, c)| *c == cname)
                .map(|(a, _)| format!("ctor {}", hex(*a as u64)))
                .chain(m.dtors.iter().filter(|(_, c)| *c == cname).map(|(a, _)| format!("dtor {}", hex(*a as u64))))
                .chain(m.scalar_dtors.iter().filter(|(_, c)| *c == cname).map(|(a, _)| format!("deleting-dtor {}", hex(*a as u64))))
                .collect();
            if !structors.is_empty() {
                let _ = writeln!(s, "    {}", structors.join("  "));
            }
        }

        // Fields: union of observed accesses and named members.
        let observed = w.fields.get(cname);
        let named = r.named_fields.get(cname);
        let mut offs: BTreeSet<i32> = BTreeSet::new();
        if let Some(o) = observed {
            offs.extend(o.keys());
        }
        if let Some(n) = named {
            offs.extend(n.keys());
        }
        if !offs.is_empty() {
            let _ = writeln!(s, "    fields:");
        }
        for off in offs {
            let st = observed.and_then(|o| o.get(&off));
            let nfs: &[crate::dump::NamedField] = named.and_then(|n| n.get(&off)).map(|v| v.as_slice()).unwrap_or(&[]);
            let nf = nfs.first();
            let size = nf
                .map(|n| n.size)
                .filter(|s| *s > 0)
                .or_else(|| st.and_then(|x| x.sizes.iter().next_back().copied().map(|v| v as u64)))
                .map(|v| format!("{v:>3}"))
                .unwrap_or_else(|| "  ?".into());
            let ty = st.map(|x| x.type_hint()).unwrap_or_else(|| "-".into());
            let rw = st.map(|x| format!("r{} w{} a{}", x.reads, x.writes, x.addr)).unwrap_or_else(|| "not seen".into());
            let nfuncs = st.map(|x| x.funcs.len()).unwrap_or(0);
            let mut name = String::new();
            if let Some(n) = nf {
                let tag = match n.source {
                    NameSrc::Bindings => "B",
                    NameSrc::Signature => "S",
                    _ => "U",
                };
                let _ = write!(name, "{} [{tag}]", n.name);
                if !n.ty.is_empty() {
                    let _ = write!(name, " : {}", n.ty);
                }
            }
            if let Some(x) = st {
                if !x.getters.is_empty() || !x.setters.is_empty() {
                    let acc: Vec<String> = x.getters.iter().chain(x.setters.iter()).cloned().collect();
                    let _ = write!(name, " ({})", acc.join(", "));
                }
            }
            let _ = writeln!(s, "      {:<8} {size} {:<10} {:<18} {:>4}  {}", hex(off as u64), ty, rw, nfuncs, name.trim());
            for extra in nfs.iter().skip(1) {
                let _ = writeln!(s, "      {:<8} {:>3} {:<10} {:<18} {:>4}  {} : {}", "", extra.size, "", "", "", extra.name, extra.ty);
            }
        }
        let _ = writeln!(s);
    }
    s
}

pub fn vtables_txt(r: &Report) -> String {
    let mut s = String::new();
    header(r, &mut s);
    let w = &r.world;
    for (mi, m) in w.modules.iter().enumerate() {
        let _ = writeln!(s, "################ {} ################\n", m.pe.name);
        for c in m.rtti.classes.values() {
            if c.vtables.is_empty() {
                continue;
            }
            for v in &c.vtables {
                let _ = writeln!(s, "{} vtable {} (subobject +{}, {} slots)", c.name, hex(v.rva as u64), hex(v.offset as u64), v.entries.len());
                for (i, &e) in v.entries.iter().enumerate() {
                    let (name, from) = w.slot_name(mi, &c.name, v.offset, i, e);
                    let (t, delta) = m.resolve_entry(e);
                    let mut note = String::new();
                    if let Some(iat) = m.entry_import(e).or_else(|| m.entry_import(t)) {
                        let dll = m.pe.import_at_iat(iat).map(|x| x.dll.clone()).unwrap_or_default();
                        let _ = write!(note, "  [import {dll}]");
                    } else if let Some(f) = from {
                        let _ = write!(note, "  [inherited from {f}]");
                    }
                    if delta != 0 {
                        let d = if delta < 0 { format!("-{:#x}", -(delta as i64)) } else { format!("+{delta:#x}") };
                        let _ = write!(note, "  [thunk this{d} -> {}]", hex(t as u64));
                    }
                    let _ = writeln!(s, "  [{i:>3}] +{:<6} {:<10} {name}{note}", format!("{:#x}", i * 8), hex(e as u64));
                }
                let _ = writeln!(s);
            }
        }
    }
    s
}

pub fn functions_txt(r: &Report) -> String {
    let mut s = String::new();
    header(r, &mut s);
    for m in &r.world.modules {
        let named = m.code.funcs.keys().filter(|a| m.names.contains_key(a)).count();
        let _ = writeln!(s, "################ {} — {} functions, {} named ################", m.pe.name, m.code.funcs.len(), named);
        let _ = writeln!(s, "  rva        size    source     name  [owner class]");
        for (&a, f) in &m.code.funcs {
            let n = m.names.get(&a);
            let src = n.map(|n| n.source.label()).unwrap_or("-");
            let mut extra = String::new();
            if let Some(o) = m.owner.get(&a) {
                let nm = n.map(|n| n.name.as_str()).unwrap_or("");
                if !nm.starts_with(&format!("{}::", o.class)) {
                    let _ = write!(extra, "  [this: {}{}]", o.class, if o.adj != 0 { format!("+{:#x}", o.adj) } else { String::new() });
                }
            }
            match f.trivial {
                Some(Trivial::Getter { off, .. }) => {
                    let _ = write!(extra, "  {{return this->[{off:#x}]}}");
                }
                Some(Trivial::RefGetter { off }) => {
                    let _ = write!(extra, "  {{return &this->[{off:#x}]}}");
                }
                Some(Trivial::Setter { off, .. }) => {
                    let _ = write!(extra, "  {{this->[{off:#x}] = arg}}");
                }
                Some(Trivial::ReturnConst(v)) => {
                    let _ = write!(extra, "  {{return {v:#x}}}");
                }
                _ => {}
            }
            if let Some(al) = m.aliases.get(&a) {
                if al.len() > 1 {
                    let _ = write!(extra, "  (folded: {} names)", al.len());
                }
            }
            let _ = writeln!(s, "  {:<10} {:<7} {:<10} {}{}", hex(a as u64), hex((f.end - f.start) as u64), src, func_name(m, a), extra);
        }
        let _ = writeln!(s);
    }
    s
}

pub fn globals_txt(r: &Report) -> String {
    let mut s = String::new();
    header(r, &mut s);
    for (mi, m) in r.world.modules.iter().enumerate() {
        #[derive(Default)]
        struct G {
            reads: u32,
            writes: u32,
            addr: u32,
            sizes: BTreeSet<u8>,
            funcs: BTreeSet<u32>,
        }
        let mut gs: BTreeMap<u32, G> = BTreeMap::new();
        for f in m.code.funcs.values() {
            for rr in &f.rip_refs {
                let Some(sec) = m.pe.section_of(rr.target) else { continue };
                if !sec.is_write() {
                    continue;
                }
                let g = gs.entry(rr.target).or_default();
                match rr.kind {
                    Access::Read => g.reads += 1,
                    Access::Write => g.writes += 1,
                    Access::Addr => g.addr += 1,
                }
                if rr.size > 0 && rr.kind != Access::Addr {
                    g.sizes.insert(rr.size);
                }
                g.funcs.insert(f.start);
            }
        }
        let _ = writeln!(s, "################ {} — {} globals in writable sections ################", m.pe.name, gs.len());
        let _ = writeln!(s, "  rva        sizes    reads/writes/addr   #funcs  name / first user");
        for (a, g) in gs {
            let name = r.named_globals.get(&(mi, a)).cloned().unwrap_or_default();
            let first = g.funcs.iter().next().map(|f| func_name(m, *f)).unwrap_or_default();
            let sizes: Vec<String> = g.sizes.iter().map(|x| x.to_string()).collect();
            let _ = writeln!(
                s,
                "  {:<10} {:<8} r{:<5} w{:<5} a{:<5} {:>5}  {}",
                hex(a as u64),
                sizes.join(","),
                g.reads,
                g.writes,
                g.addr,
                g.funcs.len(),
                if name.is_empty() { format!("(used by {first})") } else { name }
            );
        }
        let _ = writeln!(s);
    }
    s
}

pub fn strings_txt(r: &Report) -> String {
    let mut s = String::new();
    header(r, &mut s);
    for m in &r.world.modules {
        let mut refs: BTreeMap<u32, BTreeSet<u32>> = BTreeMap::new();
        for f in m.code.funcs.values() {
            for rr in &f.rip_refs {
                if rr.kind == Access::Addr && m.pe.section_of(rr.target).is_some_and(|x| !x.is_exec() && !x.is_write()) {
                    refs.entry(rr.target).or_default().insert(f.start);
                }
            }
        }
        let _ = writeln!(s, "################ {} ################", m.pe.name);
        let _ = writeln!(s, "  string rva   referenced by");
        for (a, fs) in refs {
            let Some(text) = ascii_at(m, a) else { continue };
            let users: Vec<String> = fs.iter().take(6).map(|f| format!("{} ({})", func_name(m, *f), hex(*f as u64))).collect();
            let more = if fs.len() > 6 { format!(" +{} more", fs.len() - 6) } else { String::new() };
            let _ = writeln!(s, "  {:<10} {:?}\n               <- {}{}", hex(a as u64), text, users.join(", "), more);
        }
        let _ = writeln!(s);
    }
    s
}

fn ascii_at(m: &Module, rva: u32) -> Option<String> {
    let b = m.pe.bytes(rva, 512);
    let n = b.iter().position(|&c| c == 0)?;
    if n < 3 {
        return None;
    }
    let t = &b[..n];
    if !t.iter().all(|&c| c == b'\t' || c == b'\n' || c == b'\r' || (0x20..0x7f).contains(&c)) {
        return None;
    }
    Some(String::from_utf8_lossy(t).into_owned())
}

pub fn imports_exports_txt(r: &Report) -> String {
    let mut s = String::new();
    header(r, &mut s);
    for m in &r.world.modules {
        let _ = writeln!(s, "################ {} imports ({}) ################", m.pe.name, m.pe.imports.len());
        let _ = writeln!(s, "  IAT slot   dll                      name");
        for i in &m.pe.imports {
            let n = i.name.as_deref().map(names::demangle).unwrap_or_else(|| format!("#{}", i.ordinal.unwrap_or(0)));
            let _ = writeln!(s, "  {:<10} {:<24} {}", hex(i.iat_rva as u64), i.dll, n);
        }
        let _ = writeln!(s);
        if !m.pe.exports.is_empty() {
            let _ = writeln!(s, "################ {} exports ({}) ################", m.pe.name, m.pe.exports.len());
            let _ = writeln!(s, "  rva        ord    name");
            let mut ex = m.pe.exports.clone();
            ex.sort_by_key(|e| e.rva);
            for e in ex {
                let n = e.name.as_deref().map(names::demangle).unwrap_or_default();
                let fw = e.forwarder.map(|f| format!("  -> {f}")).unwrap_or_default();
                let _ = writeln!(s, "  {:<10} {:<6} {n}{fw}", hex(e.rva as u64), e.ordinal);
            }
            let _ = writeln!(s);
        }
    }
    s
}

fn json(r: &Report) -> serde_json::Value {
    use serde_json::{Value, json};
    let w = &r.world;
    let mut modules = Vec::new();
    for (mi, m) in w.modules.iter().enumerate() {
        let mut classes = serde_json::Map::new();
        for c in m.rtti.classes.values() {
            let vts: Vec<Value> = c
                .vtables
                .iter()
                .map(|v| {
                    json!({
                        "rva": v.rva, "offset": v.offset,
                        "slots": v.entries.iter().enumerate().map(|(i, &e)| json!({"rva": e, "name": w.slot_name(mi, &c.name, v.offset, i, e).0})).collect::<Vec<_>>()
                    })
                })
                .collect();
            let fields: Vec<Value> = w
                .fields
                .get(&c.name)
                .map(|f| {
                    f.iter()
                        .map(|(o, st)| {
                            let named = r.named_fields.get(&c.name).and_then(|n| n.get(o)).and_then(|n| n.first()).map(|n| n.name.clone());
                            json!({"offset": o, "sizes": st.sizes, "type": st.type_hint(), "reads": st.reads, "writes": st.writes, "name": named})
                        })
                        .collect()
                })
                .unwrap_or_default();
            let named: Vec<Value> = r
                .named_fields
                .get(&c.name)
                .map(|n| {
                    n.iter().flat_map(|(o, v)| v.iter().map(move |f| json!({"offset": o, "name": f.name, "type": f.ty, "size": f.size}))).collect()
                })
                .unwrap_or_default();
            classes.insert(
                c.name.clone(),
                json!({
                    "size": w.size_of(&c.name),
                    "typeinfo": c.td_rva,
                    "bases": c.direct_bases.iter().map(|b| json!({"name": b.name, "offset": b.mdisp})).collect::<Vec<_>>(),
                    "vtables": vts,
                    "observed_fields": fields,
                    "named_fields": named,
                }),
            );
        }
        let funcs: Vec<Value> =
            m.code.funcs.keys().filter_map(|a| m.names.get(a).map(|n| json!({"rva": a, "name": n.name, "source": n.source.label()}))).collect();
        let singletons: Vec<Value> = m.singletons.iter().map(|s| json!({"class": s.class, "global": s.global, "accessor": s.accessor, "size": s.size})).collect();
        modules.push(json!({
            "name": m.pe.name, "timestamp": m.pe.timestamp, "image_base": m.pe.image_base,
            "classes": classes, "functions": funcs, "singletons": singletons,
        }));
    }
    json!({ "generator": format!("gddumper {}", env!("CARGO_PKG_VERSION")), "modules": modules })
}
